FROM php:8.1-fpm
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y git zip unzip libpq-dev && docker-php-ext-install pdo pdo_pgsql
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY . .
RUN composer install --no-interaction --prefer-dist --optimize-autoloader \
    && php artisan key:generate \
    && php artisan migrate --force || true
CMD ["php-fpm"]
EXPOSE 8000
